### ISSUE TITLE
Posting this mod to curseforge or modrinth?

### ISSUE THREAD

**Issue by CebbyS** [natanfudge/artifice#36]
When 2 different mods use your library included in the jar file it causes a DLL hell issue when two different versions of artifice clash. If it would be posted on curseforge, the mod can easily be added to modpacks and can be used between multiple mods, without any includes. This is just my opinion.

Kind regards, CebbyS!

**Comment by natanfudge** [comment]
When two different versions of tbe same mod are included, only the latest one is used. This has the same benefits as distributing the mod separately. If two different mods clash because of different artifice versions, they would still clash when a singular artifice jar is added separately (no matter if it matches the first or second mod's version, or if it's a different version altogether)
